### ISSUE TITLE
Docs describe `SelectVertex` which doesn;t exist

### ISSUE THREAD

**Issue by chris-major-improbable** [improbable-research/keanu#223]
**Describe the bug**
https://github.com/improbable-research/keanu/blob/develop/keanu-docs/docs/vertices.md lists an example for a SelectVertex - yet it doesn't exist in code.

**To Reproduce**
1. Go to 'https://github.com/improbable-research/keanu/blob/develop/keanu-docs/docs/vertices.md'
2. Look at the code example `return new SelectVertex<MyType>(frequency);`
3. Try to use in latest version
4. Does not compile

**Expected behavior**
I think the functionality is actually in `CategoricalVertex` so might just be a docs update

**Comment by christophernorth** [comment]
Thanks for the input - We're in the middle of a major refactor of the documentation so this will be resolved fully when we fold that in (and code in the documentation will actually be compiled and verified such that it always builds/runs at this point too).

Sorry for this - I'll get this particular example fixed in the meantime though so we don't have this hanging around until everything is pulled together.
